#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for gpopt
#
#-------------------------------------------------------------------------

subdir = src/backend/px_optimizer_util/relcache
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/src/backend/px_optimizer_util/px_optimizer_util.mk

OBJS = CMDProviderRelcache.o

include $(top_srcdir)/src/backend/common.mk
