#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for pool
#
#  Portions Copyright (c) 2010-2012 Postgres-XC Development Group
#
# IDENTIFICATION
#    $PostgreSQL$
#
#-------------------------------------------------------------------------

subdir = src/backend/polardbx/connection
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = pool


OBJS = pgxcnode.o


include $(top_srcdir)/src/backend/common.mk
