#
# Makefile for optimizer
#
# src/backend/px_optimizer/libgpopt/src/base/Makefile
#

subdir = src/backend/px_optimizer/libgpopt/src/base
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/src/backend/px_optimizer/px_optimizer.mk

OBJS        = CAutoOptCtxt.o \
              CCTEInfo.o \
              CCTEMap.o \
              CCTEReq.o \
              CCastUtils.o \
              CColConstraintsArrayMapper.o \
              CColConstraintsHashMapper.o \
              CColRef.o \
              CColRefComputed.o \
              CColRefSet.o \
              CColRefSetIter.o \
              CColRefTable.o \
              CColumnFactory.o \
              CConstraint.o \
              CConstraintConjunction.o \
              CConstraintDisjunction.o \
              CConstraintInterval.o \
              CConstraintNegation.o \
              CCostContext.o \
              CDatumSortedSet.o \
              CDefaultComparator.o \
              CDistributionSpecHashed.o \
              CDistributionSpecHashedNoOp.o \
              CDistributionSpecNonSingleton.o \
              CDistributionSpecRandom.o \
              CDistributionSpecReplicated.o \
              CDistributionSpecRouted.o \
              CDistributionSpecSingleton.o \
              CDistributionSpecStrictHashed.o \
              CDistributionSpecStrictRandom.o \
              CDistributionSpecStrictSingleton.o \
              CDistributionSpecUniversal.o \
              CDrvdProp.o \
              CDrvdPropCtxt.o \
              CDrvdPropCtxtPlan.o \
              CDrvdPropPlan.o \
              CDrvdPropRelational.o \
              CDrvdPropScalar.o \
              CEnfdDistribution.o \
              CEnfdOrder.o \
              CEnfdPartitionPropagation.o \
              CEnfdProp.o \
              CEnfdRewindability.o \
              CFunctionProp.o \
              CFunctionalDependency.o \
              CIOUtils.o \
              CKeyCollection.o \
              COptCtxt.o \
              COptimizationContext.o \
              COrderSpec.o \
              CPartInfo.o \
              CPartKeys.o \
              CPartitionPropagationSpec.o \
              CPrintPrefix.o \
              CPropConstraint.o \
              CQueryContext.o \
              CRange.o \
              CReqdProp.o \
              CReqdPropPlan.o \
              CReqdPropRelational.o \
              CRewindabilitySpec.o \
              CUtils.o \
              CWindowFrame.o \
              CWindowOids.o \
              IColConstraintsMapper.o \
              CPolarUtils.o

include $(top_srcdir)/src/backend/common.mk

