#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for pool
#
#  Portions Copyright (c) 2010-2012 Postgres-XC Development Group
#
# IDENTIFICATION
#    $PostgreSQL$
#
#-------------------------------------------------------------------------

subdir = src/backend/polardbx/executor
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = execRemoteQuery.o recvRemote.o

include $(top_srcdir)/src/backend/common.mk
