#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for locator and data distribution
#
# Copyright(C) 2010-2012 Postgres-XC Development Group
#
# IDENTIFICATION
#    $PostgreSQL$
#
#-------------------------------------------------------------------------

subdir = src/backend/polardbx/mdcache
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = mdcache.o 

include $(top_srcdir)/src/backend/common.mk
