#
# Makefile for optimizer
#
# src/backend/px_optimizer/libgpopt/src/search/Makefile
#

subdir = src/backend/px_optimizer/libgpopt/src/search
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/src/backend/px_optimizer/px_optimizer.mk

OBJS        = CBinding.o \
              CGroup.o \
              CGroupExpression.o \
              CGroupProxy.o \
              CJob.o \
              CJobFactory.o \
              CJobGroup.o \
              CJobGroupExploration.o \
              CJobGroupExpression.o \
              CJobGroupExpressionExploration.o \
              CJobGroupExpressionImplementation.o \
              CJobGroupExpressionOptimization.o \
              CJobGroupImplementation.o \
              CJobGroupOptimization.o \
              CJobQueue.o \
              CJobTest.o \
              CJobTransformation.o \
              CMemo.o \
              CScheduler.o \
              CSchedulerContext.o \
              CSearchStage.o

include $(top_srcdir)/src/backend/common.mk

