#
# Makefile for optimizer
#
# src/backend/px_optimizer/libgpos/src/string/Makefile
#

subdir = src/backend/px_optimizer/libgpos/src/string
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/src/backend/px_optimizer/px_optimizer.mk

OBJS        = CStringStatic.o \
              CWString.o \
              CWStringBase.o \
              CWStringConst.o \
              CWStringDynamic.o \
              CWStringStatic.o

include $(top_srcdir)/src/backend/common.mk

