CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
CREATE ROLE test_user;
DROP ROLE test_user;
CREATE ROLE test_superuser WITH SUPERUSER;
DROP ROLE test_superuser;
