#
# Makefile for optimizer
#
# src/backend/px_optimizer/libgpopt/src/metadata/Makefile
#

subdir = src/backend/px_optimizer/libgpopt/src/metadata
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/src/backend/px_optimizer/px_optimizer.mk

OBJS        = CColumnDescriptor.o \
              CIndexDescriptor.o \
              CName.o \
              CPartConstraint.o \
              CTableDescriptor.o

include $(top_srcdir)/src/backend/common.mk

