#
# Makefile for optimizer
#
# src/backend/px_optimizer/libnaucrates/src/md/Makefile
#

subdir = src/backend/px_optimizer/libnaucrates/src/md
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/src/backend/px_optimizer/px_optimizer.mk

OBJS        = CDXLBucket.o \
              CDXLColStats.o \
              CDXLRelStats.o \
              CDXLStatsDerivedColumn.o \
              CDXLStatsDerivedRelation.o \
              CMDAggregateGPDB.o \
              CMDArrayCoerceCastGPDB.o \
              CMDCastGPDB.o \
              CMDCheckConstraintGPDB.o \
              CMDColumn.o \
              CMDFunctionGPDB.o \
              CMDIdCast.o \
              CMDIdColStats.o \
              CMDIdGPDB.o \
              CMDIdGPDBCtas.o \
              CMDIdRelStats.o \
              CMDIdScCmp.o \
              CMDIndexGPDB.o \
              CMDIndexInfo.o \
              CMDName.o \
              CMDPartConstraintGPDB.o \
              CMDProviderGeneric.o \
              CMDProviderMemory.o \
              CMDRelationCtasGPDB.o \
              CMDRelationExternalGPDB.o \
              CMDRelationGPDB.o \
              CMDRequest.o \
              CMDScCmpGPDB.o \
              CMDScalarOpGPDB.o \
              CMDTriggerGPDB.o \
              CMDTypeBoolGPDB.o \
              CMDTypeGenericGPDB.o \
              CMDTypeInt2GPDB.o \
              CMDTypeInt4GPDB.o \
              CMDTypeInt8GPDB.o \
              CMDTypeOidGPDB.o \
              CSystemId.o \
              IMDCacheObject.o \
              IMDIndex.o \
              IMDProvider.o \
              IMDRelation.o \
              IMDType.o

include $(top_srcdir)/src/backend/common.mk

