#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for distributed executor's shared memory queue
#
#  Portions Copyright (c) 2011 StormDB 
#  
# IDENTIFICATION
#    $PostgreSQL$
#
#-------------------------------------------------------------------------

subdir = src/backend/polardbx/squeue
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = squeue.o

include $(top_srcdir)/src/backend/common.mk
