#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for distributed_txn
#
# IDENTIFICATION
#    src/backend/distributed_txn/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/distributed_txn
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = logical_clock.o txn_timestamp.o

include $(top_srcdir)/src/backend/common.mk
