#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for node management routines
#
#  Portions Copyright (c) 2010-2012 Postgres-XC Development Group
#
# IDENTIFICATION
#    $PostgreSQL$
#
#-------------------------------------------------------------------------

subdir = src/backend/polardbx/nodemgr
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = nodemgr.o 

include $(top_srcdir)/src/backend/common.mk
