#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/list
#
# IDENTIFICATION
#    src/backend/utils/list/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/list
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = polar_successor_list.o

include $(top_srcdir)/src/backend/common.mk
