#
# Makefile for optimizer
#
# src/backend/px_optimizer/libgpopt/src/optimizer/Makefile
#

subdir = src/backend/px_optimizer/libgpopt/src/optimizer
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/src/backend/px_optimizer/px_optimizer.mk

OBJS        = COptimizer.o COptimizerConfig.o

include $(top_srcdir)/src/backend/common.mk

