subdir = src/backend/utils/resource_manager
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS =  memquota.o
# OBJS += resource_manager.o
include $(top_srcdir)/src/backend/common.mk
