#
# Makefile for optimizer
#
# src/backend/px_optimizer/libgpopt/src/mdcache/Makefile
#

subdir = src/backend/px_optimizer/libgpopt/src/mdcache
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/src/backend/px_optimizer/px_optimizer.mk

OBJS        = CMDAccessor.o \
              CMDAccessorUtils.o \
              CMDCache.o \
              CMDKey.o

include $(top_srcdir)/src/backend/common.mk

