#----------------------------------------------------------------------------
#
# Postgres-XC backend method makefile
#
# Copyright(c) 2010-2012 Postgres-XC Development Group
#
# src/backend/pgxc/Makefile
#
#-----------------------------------------------------------------------------
subdir = src/backend/polardbx
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = mdcache nodemgr locator executor connection squeue transam

include $(top_srcdir)/src/backend/common.mk
