#
# Makefile for optimizer
#
# src/backend/px_optimizer/libgpos/src/test/Makefile
#

subdir = src/backend/px_optimizer/libgpos/src/memory
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/src/backend/px_optimizer/px_optimizer.mk

include $(top_srcdir)/src/backend/common.mk


