#-------------------------------------------------------------------------
#
# Makefile for src/backend/polar_dma/libconsensus/polar_wrapper
#
# Copyright (c) 2022, Alibaba Group Holding Limited
#
# src/backend/polar_dma/libconsensus/polar_wrapper/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/polar_dma/libconsensus/polar_wrapper
top_builddir = ../../../../..
include $(top_builddir)/src/Makefile.global
include $(top_srcdir)/src/backend/polar_dma/polar_dma.mk

OBJS = polar_consensus_log.o \
	   polar_consensus_c.o

include $(top_srcdir)/src/backend/common.mk
