# Makefile for optimizer
#
# src/backend/px_optimizer/Makefile
#

subdir = src/backend/px_optimizer
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS     = libgpos libgpdbcost libnaucrates libgpopt

include $(top_srcdir)/src/backend/common.mk
