language: cpp
before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install cmake; fi
script: 
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
notifications:
  recipients:
    - i@yanyiwu.com
  email:
    on_success: change
    on_failure: always
