#
# Makefile for optimizer
#
# src/backend/px_optimizer/libgpopt/Makefile
#

subdir = src/backend/px_optimizer/libgpopt
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS     = src

include $(top_srcdir)/src/backend/common.mk
