create user user_with_createrole with createrole;
create user polaruser polar_superuser;
set session authorization 'user_with_createrole';
create user normal_user1;
grant pg_read_all_settings to normal_user1;
revoke pg_read_all_settings from normal_user1;
grant pg_read_all_stats to normal_user1;
revoke pg_read_all_stats from normal_user1;
grant pg_stat_scan_tables to normal_user1;
revoke pg_stat_scan_tables from normal_user1;
grant pg_monitor to normal_user1;
revoke pg_monitor from normal_user1;
grant pg_signal_backend to normal_user1;
revoke pg_signal_backend from normal_user1;
grant pg_read_server_files to normal_user1;
revoke pg_read_server_files from normal_user1;
grant pg_write_server_files to normal_user1;
revoke pg_write_server_files from normal_user1;
grant pg_execute_server_program to normal_user1;
revoke pg_execute_server_program from normal_user1;
grant pg_polar_superuser to normal_user1;
revoke pg_polar_superuser from normal_user1;
set session authorization 'polaruser';
create user normal_user2;
grant pg_read_all_settings to normal_user2;
revoke pg_read_all_settings from normal_user2;
grant pg_read_all_stats to normal_user2;
revoke pg_read_all_stats from normal_user2;
grant pg_stat_scan_tables to normal_user2;
revoke pg_stat_scan_tables from normal_user2;
grant pg_monitor to normal_user2;
revoke pg_monitor from normal_user2;
grant pg_signal_backend to normal_user2;
revoke pg_signal_backend from normal_user2;
grant pg_read_server_files to normal_user2;
revoke pg_read_server_files from normal_user2;
grant pg_write_server_files to normal_user2;
revoke pg_write_server_files from normal_user2;
grant pg_execute_server_program to normal_user2;
revoke pg_execute_server_program from normal_user2;
grant pg_polar_superuser to normal_user2;
revoke pg_polar_superuser from normal_user2;

select pg_has_role('pg_signal_backend','USAGE');
select pg_has_role('pg_signal_backend','MEMBER');
select pg_has_role('pg_signal_backend','USAGE WITH GRANT OPTION');

reset session authorization;
drop user normal_user1;
drop user normal_user2;
drop user user_with_createrole;
drop user polaruser;