name: docs format check

on:
  # trigger deployment on every PR to branch POLARDB_11_DEV in docs/
  pull_request:
    branches: [ POLARDB_11_DEV ]
    paths:
      - ".github/workflows/docs.yml"
      - "docs/**"
      - "package*"
  # trigger deployment manually
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # fetch all commits to get last updated time or other git log info
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          # choose pnpm version to use
          version: 8
          # install deps with pnpm
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # choose node.js version to use
          node-version: 20
          # cache deps for pnpm
          cache: pnpm

      - name: Prettier check
        run: pnpm prettier:check
