name: sync with postgres upstream

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: repo-sync-master
        uses: repo-sync/github-sync@v2
        with:
          source_repo: https://github.com/postgres/postgres.git
          source_branch: master
          destination_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: repo-sync-17
        uses: repo-sync/github-sync@v2
        with:
          source_repo: https://github.com/postgres/postgres.git
          source_branch: REL_17_STABLE
          destination_branch: REL_17_STABLE
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: repo-sync-16
        uses: repo-sync/github-sync@v2
        with:
          source_repo: https://github.com/postgres/postgres.git
          source_branch: REL_16_STABLE
          destination_branch: REL_16_STABLE
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: repo-sync-15
        uses: repo-sync/github-sync@v2
        with:
          source_repo: https://github.com/postgres/postgres.git
          source_branch: REL_15_STABLE
          destination_branch: REL_15_STABLE
          github_token: ${{ secrets.GITHUB_TOKEN }}
